# Generated by Django 5.0.6 on 2024-07-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0004_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8),
        ),
    ]
