# Generated by Django 5.0.6 on 2024-07-05 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rentalcar',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
