# Generated by Django 5.0.6 on 2024-06-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicestation',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='servicestation',
            name='mechanics',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Mechanic',
        ),
        migrations.DeleteModel(
            name='ServiceStation',
        ),
    ]
