# Generated by Django 5.0.6 on 2024-06-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('manager', 'Manager')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='specialization',
            field=models.CharField(choices=[('engine', 'Engine'), ('brakes', 'Brakes'), ('electrical', 'Electrical')], max_length=100),
        ),
    ]
