# Generated by Django 5.0.6 on 2024-06-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_admin_role_alter_mechanic_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestation',
            name='rating',
            field=models.CharField(max_length=255),
        ),
    ]
