# Generated by Django 5.0.6 on 2024-06-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_servicestation_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestation',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='servicestation',
            name='services_offered',
            field=models.CharField(max_length=255),
        ),
    ]
