# Generated by Django 5.0.6 on 2024-06-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_alter_servicestation_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestation',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='servicestationphotos/'),
        ),
        migrations.AddField(
            model_name='servicestation',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='servicestationphotos/'),
        ),
        migrations.AddField(
            model_name='servicestation',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='servicestationphotos/'),
        ),
        migrations.AddField(
            model_name='servicestation',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='servicestationphotos/'),
        ),
    ]
