# Generated by Django 5.0.6 on 2024-06-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_servicestation_photo1_servicestation_photo2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicestation',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='servicestation',
            name='mechanics',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Mechanic',
        ),
        migrations.DeleteModel(
            name='ServiceStation',
        ),
    ]
