# Generated by Django 5.0.6 on 2024-06-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Work Done', 'Work Done')], default='Pending', max_length=20),
        ),
    ]
