# Generated by Django 5.0.6 on 2024-07-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='problem_description',
            field=models.CharField(max_length=300),
        ),
    ]
