# Generated by Django 5.0.6 on 2024-07-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0007_alter_servicerequest_problem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(max_length=100),
        ),
    ]
