# Generated by Django 5.0.6 on 2024-07-04 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0008_alter_feedback_feedback'),
        ('mechanic_management', '0007_alter_mechanic_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='assigned_mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='mechanic_management.mechanic'),
        ),
    ]
