# Generated by Django 5.0.6 on 2024-07-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0009_servicerequest_assigned_mechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('car_wash', 'Car Wash'), ('oil_change', 'Oil Change'), ('brake_service', 'Brake Service'), ('spare_part_work', 'Spare Part Work'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
