# Generated by Django 5.0.6 on 2024-07-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0010_servicerequest_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('car wash', 'Car Wash'), ('oil change', 'Oil Change'), ('brake service', 'Brake Service'), ('spare part_work', 'Spare Part Work'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
