# Generated by Django 5.0.6 on 2024-06-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_management', '0002_alter_mechanicwork_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicwork',
            name='status',
            field=models.CharField(choices=[('Repairing', 'Repairing'), ('Repairing Done', 'Repairing Done'), ('Released', 'Released')], default='Repairing', max_length=20),
        ),
    ]
