# Generated by Django 5.0.6 on 2024-06-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_management', '0003_alter_mechanicwork_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicwork',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
