# Generated by Django 5.0.6 on 2024-06-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_management', '0005_mechanicearnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicearnings',
            name='admin_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
