# Generated by Django 5.0.6 on 2024-07-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_management', '0006_mechanicearnings_admin_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
