# Generated by Django 5.0.6 on 2024-07-05 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_management', '0007_alter_mechanic_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
