# Generated by Django 5.0.6 on 2024-07-05 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_management', '0008_mechanic_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicwork',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
