# Generated by Django 5.0.6 on 2024-07-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_management', '0009_mechanicwork_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanicwork',
            name='created_at',
        ),
    ]
